// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: streaming.proto

package StreamMessage;

public final class Streaming {
  private Streaming() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MsgProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:StreamMessage.MsgProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * subject
     * </pre>
     *
     * <code>string subject = 2;</code>
     * @return The subject.
     */
    java.lang.String getSubject();
    /**
     * <pre>
     * subject
     * </pre>
     *
     * <code>string subject = 2;</code>
     * @return The bytes for subject.
     */
    com.google.protobuf.ByteString
        getSubjectBytes();

    /**
     * <pre>
     * payload
     * </pre>
     *
     * <code>bytes data = 3;</code>
     * @return The data.
     */
    com.google.protobuf.ByteString getData();

    /**
     * <pre>
     * received timestamp
     * </pre>
     *
     * <code>int64 timestamp = 4;</code>
     * @return The timestamp.
     */
    long getTimestamp();

    /**
     * <pre>
     * customer id to which this data belongs
     * </pre>
     *
     * <code>string customer_id = 5;</code>
     * @return The customerId.
     */
    java.lang.String getCustomerId();
    /**
     * <pre>
     * customer id to which this data belongs
     * </pre>
     *
     * <code>string customer_id = 5;</code>
     * @return The bytes for customerId.
     */
    com.google.protobuf.ByteString
        getCustomerIdBytes();

    /**
     * <pre>
     * optional field indicating the msp_id 
     * </pre>
     *
     * <code>string msp_id = 6;</code>
     * @return The mspId.
     */
    java.lang.String getMspId();
    /**
     * <pre>
     * optional field indicating the msp_id 
     * </pre>
     *
     * <code>string msp_id = 6;</code>
     * @return The bytes for mspId.
     */
    com.google.protobuf.ByteString
        getMspIdBytes();
  }
  /**
   * Protobuf type {@code StreamMessage.MsgProto}
   */
  public static final class MsgProto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:StreamMessage.MsgProto)
      MsgProtoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MsgProto.newBuilder() to construct.
    private MsgProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MsgProto() {
      subject_ = "";
      data_ = com.google.protobuf.ByteString.EMPTY;
      customerId_ = "";
      mspId_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MsgProto();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MsgProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              subject_ = s;
              break;
            }
            case 26: {

              data_ = input.readBytes();
              break;
            }
            case 32: {

              timestamp_ = input.readInt64();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              customerId_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              mspId_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return StreamMessage.Streaming.internal_static_StreamMessage_MsgProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return StreamMessage.Streaming.internal_static_StreamMessage_MsgProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              StreamMessage.Streaming.MsgProto.class, StreamMessage.Streaming.MsgProto.Builder.class);
    }

    public static final int SUBJECT_FIELD_NUMBER = 2;
    private volatile java.lang.Object subject_;
    /**
     * <pre>
     * subject
     * </pre>
     *
     * <code>string subject = 2;</code>
     * @return The subject.
     */
    @java.lang.Override
    public java.lang.String getSubject() {
      java.lang.Object ref = subject_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        subject_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * subject
     * </pre>
     *
     * <code>string subject = 2;</code>
     * @return The bytes for subject.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSubjectBytes() {
      java.lang.Object ref = subject_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        subject_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString data_;
    /**
     * <pre>
     * payload
     * </pre>
     *
     * <code>bytes data = 3;</code>
     * @return The data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 4;
    private long timestamp_;
    /**
     * <pre>
     * received timestamp
     * </pre>
     *
     * <code>int64 timestamp = 4;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int CUSTOMER_ID_FIELD_NUMBER = 5;
    private volatile java.lang.Object customerId_;
    /**
     * <pre>
     * customer id to which this data belongs
     * </pre>
     *
     * <code>string customer_id = 5;</code>
     * @return The customerId.
     */
    @java.lang.Override
    public java.lang.String getCustomerId() {
      java.lang.Object ref = customerId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        customerId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * customer id to which this data belongs
     * </pre>
     *
     * <code>string customer_id = 5;</code>
     * @return The bytes for customerId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCustomerIdBytes() {
      java.lang.Object ref = customerId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        customerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSP_ID_FIELD_NUMBER = 6;
    private volatile java.lang.Object mspId_;
    /**
     * <pre>
     * optional field indicating the msp_id 
     * </pre>
     *
     * <code>string msp_id = 6;</code>
     * @return The mspId.
     */
    @java.lang.Override
    public java.lang.String getMspId() {
      java.lang.Object ref = mspId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mspId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * optional field indicating the msp_id 
     * </pre>
     *
     * <code>string msp_id = 6;</code>
     * @return The bytes for mspId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMspIdBytes() {
      java.lang.Object ref = mspId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mspId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSubjectBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, subject_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(3, data_);
      }
      if (timestamp_ != 0L) {
        output.writeInt64(4, timestamp_);
      }
      if (!getCustomerIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, customerId_);
      }
      if (!getMspIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, mspId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSubjectBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, subject_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, data_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, timestamp_);
      }
      if (!getCustomerIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, customerId_);
      }
      if (!getMspIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, mspId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof StreamMessage.Streaming.MsgProto)) {
        return super.equals(obj);
      }
      StreamMessage.Streaming.MsgProto other = (StreamMessage.Streaming.MsgProto) obj;

      if (!getSubject()
          .equals(other.getSubject())) return false;
      if (!getData()
          .equals(other.getData())) return false;
      if (getTimestamp()
          != other.getTimestamp()) return false;
      if (!getCustomerId()
          .equals(other.getCustomerId())) return false;
      if (!getMspId()
          .equals(other.getMspId())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SUBJECT_FIELD_NUMBER;
      hash = (53 * hash) + getSubject().hashCode();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (37 * hash) + CUSTOMER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getCustomerId().hashCode();
      hash = (37 * hash) + MSP_ID_FIELD_NUMBER;
      hash = (53 * hash) + getMspId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static StreamMessage.Streaming.MsgProto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static StreamMessage.Streaming.MsgProto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static StreamMessage.Streaming.MsgProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static StreamMessage.Streaming.MsgProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static StreamMessage.Streaming.MsgProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static StreamMessage.Streaming.MsgProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static StreamMessage.Streaming.MsgProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static StreamMessage.Streaming.MsgProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static StreamMessage.Streaming.MsgProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static StreamMessage.Streaming.MsgProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static StreamMessage.Streaming.MsgProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static StreamMessage.Streaming.MsgProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(StreamMessage.Streaming.MsgProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code StreamMessage.MsgProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:StreamMessage.MsgProto)
        StreamMessage.Streaming.MsgProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return StreamMessage.Streaming.internal_static_StreamMessage_MsgProto_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return StreamMessage.Streaming.internal_static_StreamMessage_MsgProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                StreamMessage.Streaming.MsgProto.class, StreamMessage.Streaming.MsgProto.Builder.class);
      }

      // Construct using StreamMessage.Streaming.MsgProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        subject_ = "";

        data_ = com.google.protobuf.ByteString.EMPTY;

        timestamp_ = 0L;

        customerId_ = "";

        mspId_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return StreamMessage.Streaming.internal_static_StreamMessage_MsgProto_descriptor;
      }

      @java.lang.Override
      public StreamMessage.Streaming.MsgProto getDefaultInstanceForType() {
        return StreamMessage.Streaming.MsgProto.getDefaultInstance();
      }

      @java.lang.Override
      public StreamMessage.Streaming.MsgProto build() {
        StreamMessage.Streaming.MsgProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public StreamMessage.Streaming.MsgProto buildPartial() {
        StreamMessage.Streaming.MsgProto result = new StreamMessage.Streaming.MsgProto(this);
        result.subject_ = subject_;
        result.data_ = data_;
        result.timestamp_ = timestamp_;
        result.customerId_ = customerId_;
        result.mspId_ = mspId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof StreamMessage.Streaming.MsgProto) {
          return mergeFrom((StreamMessage.Streaming.MsgProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(StreamMessage.Streaming.MsgProto other) {
        if (other == StreamMessage.Streaming.MsgProto.getDefaultInstance()) return this;
        if (!other.getSubject().isEmpty()) {
          subject_ = other.subject_;
          onChanged();
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        if (!other.getCustomerId().isEmpty()) {
          customerId_ = other.customerId_;
          onChanged();
        }
        if (!other.getMspId().isEmpty()) {
          mspId_ = other.mspId_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        StreamMessage.Streaming.MsgProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (StreamMessage.Streaming.MsgProto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object subject_ = "";
      /**
       * <pre>
       * subject
       * </pre>
       *
       * <code>string subject = 2;</code>
       * @return The subject.
       */
      public java.lang.String getSubject() {
        java.lang.Object ref = subject_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          subject_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * subject
       * </pre>
       *
       * <code>string subject = 2;</code>
       * @return The bytes for subject.
       */
      public com.google.protobuf.ByteString
          getSubjectBytes() {
        java.lang.Object ref = subject_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          subject_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * subject
       * </pre>
       *
       * <code>string subject = 2;</code>
       * @param value The subject to set.
       * @return This builder for chaining.
       */
      public Builder setSubject(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        subject_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * subject
       * </pre>
       *
       * <code>string subject = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSubject() {
        
        subject_ = getDefaultInstance().getSubject();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * subject
       * </pre>
       *
       * <code>string subject = 2;</code>
       * @param value The bytes for subject to set.
       * @return This builder for chaining.
       */
      public Builder setSubjectBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        subject_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * payload
       * </pre>
       *
       * <code>bytes data = 3;</code>
       * @return The data.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <pre>
       * payload
       * </pre>
       *
       * <code>bytes data = 3;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * payload
       * </pre>
       *
       * <code>bytes data = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <pre>
       * received timestamp
       * </pre>
       *
       * <code>int64 timestamp = 4;</code>
       * @return The timestamp.
       */
      @java.lang.Override
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <pre>
       * received timestamp
       * </pre>
       *
       * <code>int64 timestamp = 4;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * received timestamp
       * </pre>
       *
       * <code>int64 timestamp = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object customerId_ = "";
      /**
       * <pre>
       * customer id to which this data belongs
       * </pre>
       *
       * <code>string customer_id = 5;</code>
       * @return The customerId.
       */
      public java.lang.String getCustomerId() {
        java.lang.Object ref = customerId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          customerId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * customer id to which this data belongs
       * </pre>
       *
       * <code>string customer_id = 5;</code>
       * @return The bytes for customerId.
       */
      public com.google.protobuf.ByteString
          getCustomerIdBytes() {
        java.lang.Object ref = customerId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          customerId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * customer id to which this data belongs
       * </pre>
       *
       * <code>string customer_id = 5;</code>
       * @param value The customerId to set.
       * @return This builder for chaining.
       */
      public Builder setCustomerId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        customerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * customer id to which this data belongs
       * </pre>
       *
       * <code>string customer_id = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearCustomerId() {
        
        customerId_ = getDefaultInstance().getCustomerId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * customer id to which this data belongs
       * </pre>
       *
       * <code>string customer_id = 5;</code>
       * @param value The bytes for customerId to set.
       * @return This builder for chaining.
       */
      public Builder setCustomerIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        customerId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object mspId_ = "";
      /**
       * <pre>
       * optional field indicating the msp_id 
       * </pre>
       *
       * <code>string msp_id = 6;</code>
       * @return The mspId.
       */
      public java.lang.String getMspId() {
        java.lang.Object ref = mspId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          mspId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * optional field indicating the msp_id 
       * </pre>
       *
       * <code>string msp_id = 6;</code>
       * @return The bytes for mspId.
       */
      public com.google.protobuf.ByteString
          getMspIdBytes() {
        java.lang.Object ref = mspId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mspId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * optional field indicating the msp_id 
       * </pre>
       *
       * <code>string msp_id = 6;</code>
       * @param value The mspId to set.
       * @return This builder for chaining.
       */
      public Builder setMspId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        mspId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * optional field indicating the msp_id 
       * </pre>
       *
       * <code>string msp_id = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearMspId() {
        
        mspId_ = getDefaultInstance().getMspId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * optional field indicating the msp_id 
       * </pre>
       *
       * <code>string msp_id = 6;</code>
       * @param value The bytes for mspId to set.
       * @return This builder for chaining.
       */
      public Builder setMspIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        mspId_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:StreamMessage.MsgProto)
    }

    // @@protoc_insertion_point(class_scope:StreamMessage.MsgProto)
    private static final StreamMessage.Streaming.MsgProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new StreamMessage.Streaming.MsgProto();
    }

    public static StreamMessage.Streaming.MsgProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MsgProto>
        PARSER = new com.google.protobuf.AbstractParser<MsgProto>() {
      @java.lang.Override
      public MsgProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MsgProto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MsgProto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MsgProto> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public StreamMessage.Streaming.MsgProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StreamMessage_MsgProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StreamMessage_MsgProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017streaming.proto\022\rStreamMessage\"a\n\010MsgP" +
      "roto\022\017\n\007subject\030\002 \001(\t\022\014\n\004data\030\003 \001(\014\022\021\n\tt" +
      "imestamp\030\004 \001(\003\022\023\n\013customer_id\030\005 \001(\t\022\016\n\006m" +
      "sp_id\030\006 \001(\tb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_StreamMessage_MsgProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_StreamMessage_MsgProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StreamMessage_MsgProto_descriptor,
        new java.lang.String[] { "Subject", "Data", "Timestamp", "CustomerId", "MspId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
